#########################################################
# Classpath properties:
# 
# CONFIG-SERVER-PORT - default(4341)
# EUREKA.INSTANCE.HTTP.PROTOCOL - default(http) , could be given as https
# EUREKA.INSTANCE.ADDRESS - default(localhost)
# EUREKA.INSTANCE.PORT - default(4340)
# CONFIG.SERVER.LOCAL.DIR - default(your local system)
##########################################################
server:
    port: ${CONFIG-SERVER-PORT:4341}
spring:
    application:
        name: EMS-CONFIG-SERVER
    profiles:
      active:
        - dev
    cloud:
      config:
        server:
          native:
            search-locations:
            - ${CONFIG.SERVER.LOCAL.DIR:file:///C:/Users/1025376/Desktop/Projects/eduMSApplication/ems-config-properties}
management:
  endpoints:
    web:
      exposure:
        include:
        - "refresh" 
eureka:
  instance:
    hostname: ${EUREKA.INSTANCE.ADDRESS:localhost}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA.INSTANCE.HTTP.PROTOCOL:http}://${eureka.instance.hostname}:${EUREKA.INSTANCE.PORT:4340}/eureka/  
    